name: seismologycourse
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.2.0=py312h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312h06a4308_0
  - attrs=23.1.0=py312h06a4308_0
  - babel=2.11.0=py312h06a4308_0
  - beautifulsoup4=4.12.3=py312h06a4308_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h6a678d5_0
  - bottleneck=1.3.7=py312ha883a20_0
  - brotli=1.0.9=h5eee18b_8
  - brotli-bin=1.0.9=h5eee18b_8
  - brotli-python=1.0.9=py312h6a678d5_8
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cartopy=0.22.0=py312h526ad5a_0
  - certifi=2024.8.30=py312h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.2.0=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.51.0=py312h5eee18b_0
  - freetype=2.12.1=h4a9f257_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py312h06a4308_0
  - httpcore=1.0.2=py312h06a4308_0
  - httpx=0.27.0=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - imagecodecs=2023.1.23=py312h81b8100_1
  - imageio=2.33.1=py312h06a4308_0
  - ipykernel=6.28.0=py312h06a4308_0
  - ipython=8.27.0=py312h06a4308_0
  - ipywidgets=8.1.2=py312h06a4308_0
  - jedi=0.19.1=py312h06a4308_0
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.0.0=py312h06a4308_9
  - jupyter-lsp=2.2.0=py312h06a4308_0
  - jupyter_client=8.6.0=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.7.2=py312h06a4308_0
  - jupyter_events=0.10.0=py312h06a4308_0
  - jupyter_server=2.14.1=py312h06a4308_0
  - jupyter_server_terminals=0.4.4=py312h06a4308_1
  - jupyterlab=4.2.5=py312h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.10=py312h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lazy_loader=0.4=py312h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libavif=0.11.1=h5eee18b_0
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - libzopfli=1.0.3=he6710b0_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib=3.9.2=py312h06a4308_0
  - matplotlib-base=3.9.2=py312h66fe004_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mistune=2.0.4=py312h06a4308_0
  - mysql=5.7.24=h721c034_2
  - nbclient=0.8.0=py312h06a4308_0
  - nbconvert=7.10.0=py312h06a4308_0
  - nbformat=5.9.2=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - networkx=3.3=py312h06a4308_0
  - notebook=7.2.2=py312h06a4308_0
  - notebook-shim=0.2.3=py312h06a4308_0
  - numexpr=2.8.7=py312he7dcb8a_0
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.1=py312h06a4308_0
  - pandas=2.2.2=py312h526ad5a_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.4.0=py312h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - proj=9.3.1=he5811b7_0
  - prometheus_client=0.14.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312h06a4308_1
  - pylops=2.3.1=pyhd8ed1ab_0
  - pyparsing=3.1.2=py312h06a4308_0
  - pyproj=3.6.1=py312h6268720_0
  - pyqt=5.15.10=py312h6a678d5_0
  - pyqt5-sip=12.13.0=py312h5eee18b_0
  - pyshp=2.3.1=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.5=h5148396_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.16.2=py312h06a4308_0
  - python-json-logger=2.0.7=py312h06a4308_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - pyzmq=25.1.2=py312h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.5.1=py312h06a4308_0
  - qtpy=2.4.1=py312h06a4308_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.3=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.10.6=py312hb02cf49_0
  - scikit-image=0.23.2=py312h526ad5a_0
  - scikit-learn=1.5.1=py312h526ad5a_0
  - scipy=1.13.1=py312h2809609_0
  - seaborn=0.13.2=py312h06a4308_0
  - send2trash=1.8.2=py312h06a4308_0
  - setuptools=72.1.0=py312h06a4308_0
  - shapely=2.0.5=py312h1789038_0
  - sip=6.7.12=py312h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312h06a4308_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tifffile=2023.4.12=py312h06a4308_0
  - tinycss2=1.2.1=py312h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_0
  - urllib3=2.2.2=py312h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312h06a4308_2
  - wheel=0.44.0=py312h06a4308_0
  - widgetsnbextension=4.0.10=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zfp=1.0.0=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - adal==1.2.7
      - antlr4-python3-runtime==4.13.2
      - applicationinsights==0.11.10
      - argcomplete==3.3.0
      - azure-appconfiguration==1.1.1
      - azure-batch==14.2.0
      - azure-cli==2.64.0
      - azure-cli-core==2.64.0
      - azure-cli-telemetry==1.1.0
      - azure-common==1.1.28
      - azure-core==1.31.0
      - azure-cosmos==3.2.0
      - azure-data-tables==12.4.0
      - azure-datalake-store==0.0.53
      - azure-graphrbac==0.60.0
      - azure-keyvault-administration==4.4.0b2
      - azure-keyvault-certificates==4.7.0
      - azure-keyvault-keys==4.9.0b3
      - azure-keyvault-secrets==4.7.0
      - azure-mgmt-advisor==9.0.0
      - azure-mgmt-apimanagement==4.0.0
      - azure-mgmt-appconfiguration==3.0.0
      - azure-mgmt-appcontainers==2.0.0
      - azure-mgmt-applicationinsights==1.0.0
      - azure-mgmt-authorization==4.0.0
      - azure-mgmt-batch==17.3.0
      - azure-mgmt-batchai==7.0.0b1
      - azure-mgmt-billing==6.0.0
      - azure-mgmt-botservice==2.0.0
      - azure-mgmt-cdn==12.0.0
      - azure-mgmt-cognitiveservices==13.5.0
      - azure-mgmt-compute==33.0.0
      - azure-mgmt-containerinstance==10.1.0
      - azure-mgmt-containerregistry==10.3.0
      - azure-mgmt-containerservice==31.0.0
      - azure-mgmt-core==1.4.0
      - azure-mgmt-cosmosdb==9.5.1
      - azure-mgmt-databoxedge==1.0.0
      - azure-mgmt-datamigration==10.0.0
      - azure-mgmt-devtestlabs==4.0.0
      - azure-mgmt-dns==8.0.0
      - azure-mgmt-eventgrid==10.2.0b2
      - azure-mgmt-eventhub==10.1.0
      - azure-mgmt-extendedlocation==1.0.0b2
      - azure-mgmt-hdinsight==9.0.0b3
      - azure-mgmt-imagebuilder==1.3.0
      - azure-mgmt-iotcentral==10.0.0b2
      - azure-mgmt-iothub==3.0.0
      - azure-mgmt-iothubprovisioningservices==1.1.0
      - azure-mgmt-keyvault==10.3.0
      - azure-mgmt-kusto==0.3.0
      - azure-mgmt-loganalytics==13.0.0b4
      - azure-mgmt-managedservices==1.0.0
      - azure-mgmt-managementgroups==1.0.0
      - azure-mgmt-maps==2.0.0
      - azure-mgmt-marketplaceordering==1.1.0
      - azure-mgmt-media==9.0.0
      - azure-mgmt-monitor==5.0.1
      - azure-mgmt-msi==7.0.0
      - azure-mgmt-netapp==10.1.0
      - azure-mgmt-policyinsights==1.1.0b4
      - azure-mgmt-privatedns==1.0.0
      - azure-mgmt-rdbms==10.2.0b17
      - azure-mgmt-recoveryservices==3.0.0
      - azure-mgmt-recoveryservicesbackup==9.1.0
      - azure-mgmt-redhatopenshift==1.5.0
      - azure-mgmt-redis==14.4.0
      - azure-mgmt-resource==23.1.1
      - azure-mgmt-search==9.1.0
      - azure-mgmt-security==6.0.0
      - azure-mgmt-servicebus==8.2.0
      - azure-mgmt-servicefabric==2.1.0
      - azure-mgmt-servicefabricmanagedclusters==2.0.0b6
      - azure-mgmt-servicelinker==1.2.0b2
      - azure-mgmt-signalr==2.0.0b1
      - azure-mgmt-sql==4.0.0b17
      - azure-mgmt-sqlvirtualmachine==1.0.0b5
      - azure-mgmt-storage==21.2.0
      - azure-mgmt-synapse==2.1.0b5
      - azure-mgmt-trafficmanager==1.0.0
      - azure-mgmt-web==7.2.0
      - azure-monitor-query==1.2.0
      - azure-multiapi-storage==1.3.0
      - azure-storage-common==1.4.2
      - azure-synapse-accesscontrol==0.5.0
      - azure-synapse-artifacts==0.19.0
      - azure-synapse-managedprivateendpoints==0.4.0
      - azure-synapse-spark==0.2.0
      - bcrypt==4.2.0
      - bruges==0.5.4
      - chardet==5.2.0
      - colorama==0.4.6
      - cryptography==43.0.1
      - deprecated==1.2.14
      - distro==1.9.0
      - fabric==3.2.2
      - greenlet==3.1.0
      - humanfriendly==10.0
      - invoke==2.2.0
      - isodate==0.6.1
      - javaproperties==0.5.2
      - jmespath==1.0.1
      - jsondiff==2.0.0
      - knack==0.11.0
      - las==0.0.5
      - lasio==0.31
      - lxml==5.3.0
      - msal==1.30.0
      - msal-extensions==1.2.0
      - msrest==0.7.1
      - msrestazure==0.6.4.post1
      - oauthlib==3.2.2
      - obspy==1.4.1
      - paramiko==3.5.0
      - pkginfo==1.11.1
      - portalocker==2.10.1
      - pycomposefile==0.0.31
      - pygithub==1.59.1
      - pyjwt==2.9.0
      - pynacl==1.5.0
      - pyopenssl==24.2.1
      - requests-oauthlib==2.0.0
      - scp==0.13.6
      - segyio==1.9.12
      - semver==2.13.0
      - sqlalchemy==1.4.54
      - sshtunnel==0.1.5
      - striplog==0.9.2
      - tabulate==0.9.0
      - tqdm==4.67.1
      - utm==0.7.0
      - websocket-client==1.3.3
      - wellpathpy==0.5.2
      - welly==0.5.2
      - wrapt==1.16.0
      - xmltodict==0.13.0
prefix: /home/bermanu/miniconda3/envs/seismologycourse
